version: '3.3'
services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: freecell
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  backend:
    depends_on: 
      - db
    build:
      dockerfile: freecell-backend/Dockerfile
    tty: true
    ports:
      - '12000:8080'
    expose:
      - 8080
    volumes:
      - ./freecell-backend:/root/freecell-backend
volumes:
  my-db: